# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate Gaussian density
#' @param x Data vector
#' @param mu Mean vector
#' @param sigma Covariance matrix
#' @return Density value
NULL

#' Gaussian Mixture Model via EM
#' @param K Number of components
#' @param X Data matrix
#' @param theta Initial parameters
#' @return Estimated coefficients
#' 
#' @export
gmm <- function(X, K, max_iter = 100L, tol = 1e-6) {
    .Call(`_code815_gmm`, X, K, max_iter, tol)
}

#' Iteratively Reweighted Least Squares for Poisson Regression
#'
#' @param X Design matrix (n x p)
#' @param y Response vector (n x 1)
#' @return Estimated coefficients
#' @export
irwls_poisson <- function(X, y, max_iter = 25L, tol = 1e-6) {
    .Call(`_code815_irwls_poisson`, X, y, max_iter, tol)
}

loss_ridge_samp <- function(y, A, x, lambda) {
    .Call(`_code815_loss_ridge_samp`, y, A, x, lambda)
}

#' Least Squares Gradient Descent with Ridge Regularization
#'
#' @param y      A (n x 1) vector of response variables
#' @param A      A (n x p) matrix of predictor variables
#' @param x_init A (p x 1) initial vector of effect sizes
#' @param lambda Regularization parameter
#' @param alpha  Learning rate for gradient descent
#' @param max_iter Maximum number of iterations
#' @param tol    Convergence tolerance
#' @return Estimated coefficients
gradient_descent_lsq <- function(y, A, x, lambda = 1, gamma = 0.01, max_iter = 1000L, tol = 1e-6) {
    .Call(`_code815_gradient_descent_lsq`, y, A, x, lambda, gamma, max_iter, tol)
}

#' Sample from Mixture of Two Gaussians via Random Walk Metropolis
#' 
#' @param n Number of samples
#' @param mu1 Mean of first Gaussian component
#' @param mu2 Mean of second Gaussian component
#' @param sigma1 Standard deviation of first Gaussian component
#' @param sigma2 Standard deviation of second Gaussian component
#' @param w1 Weight of first Gaussian component
#' @param w2 Weight of second Gaussian component
#' @param mean_proposal Mean of proposal distribution
#' @param sigma_proposal Standard deviation of proposal distribution
#' @return Samples from mixture of two Gaussians
#' 
#' @export
rmixnorm <- function(n = 1000L, mu1 = 0, mu2 = 0, sigma1 = 1, sigma2 = 1, w1 = 0.5, w2 = 0.5, mean_proposal = 0, sigma_proposal = 1) {
    .Call(`_code815_rmixnorm`, n, mu1, mu2, sigma1, sigma2, w1, w2, mean_proposal, sigma_proposal)
}

#' Sample from Truncated Mixture of Two Gaussians via Random Walk Metropolis
#' 
#' @param n Number of samples
#' @param mu1 Mean of first Gaussian component
#' @param mu2 Mean of second Gaussian component
#' @param sigma1 Standard deviation of first Gaussian component
#' @param sigma2 Standard deviation of second Gaussian component
#' @param w1 Weight of first Gaussian component
#' @param w2 Weight of second Gaussian component
#' @param mean_proposal Mean of proposal distribution
#' @param sigma_proposal Standard deviation of proposal distribution
#' @param lower Lower bound of truncation
#' @param upper Upper bound of truncation
#' @return Samples from mixture of two Gaussians
#' 
#' @export
rtruncmixnorm <- function(n = 1000L, mu1 = 0, mu2 = 0, sigma1 = 1, sigma2 = 1, w1 = 0.5, w2 = 0.5, mean_proposal = 0, sigma_proposal = 1, lower = -1, upper = 1) {
    .Call(`_code815_rtruncmixnorm`, n, mu1, mu2, sigma1, sigma2, w1, w2, mean_proposal, sigma_proposal, lower, upper)
}

